# Taxonomy v2 (side-less, junk removed) - generated 2026-09-14
# 296 old classes -> 166 classes
nc: 166
names:
- archer
- archer_evolution
- baby_dragon
- baby_dragon_evolution
- baby_goblin_dagger
- balloon
- bandit
- barbarian
- barbarian_evolution
- bats
- bats_evolution
- battle_ram
- battle_ram_evolution
- berserker
- black_knight
- bomber
- bomber_evolution
- boss_bandit
- bowler
- barbarian_hut
- basic_cannon
- bomb_tower
- cannon_evolution
- elixir_collector
- goblin_drill
- goblin_drill_evolution
- goblin_hut
- inferno_tower
- mega_bomb
- mighty_miner_bomb_dl
- mortar
- mortar_evolution
- rage_bottle
- tesla
- tesla_evolution
- tombstone
- princess_tower
- xbow
- cannoneer
- dark_witch
- electro_dragon_evolution
- electro_wizard
- executioner
- executioner_evolution
- fire_firespirit
- firecracker_evolution
- flying_machine
- furnace_evolution
- furnace
- giant
- giant_skeleton
- goblin
- goblin_archer
- goblin_blowdart
- goblin_blowdart_evolution
- goblin_cage_evolution
- goblin_demolisher
- goblin_giant_evolution
- goblin_machine
- goblin_queen
- goblinstein_doctor
- goblinstein_monster
- golem
- golemite
- hog_rider
- hunter_evolution
- ice_spirit_evolution
- ice_spirits
- ice_wizard
- inferno_dragon_evolution
- king_tower
- knight
- knight_evolution
- knives_thrower
- lava_hound
- lava_pups
- lumberjack_evolution
- mega_knight
- mega_knight_evolution
- mega_minion
- merge_maiden
- merge_maiden_dragon
- miner
- mini_pekka
- minion
- moving_cannon
- musketeer
- musketeer_evolution
- pekka
- pekka_evolution
- prince
- princess
- rage_barbarian
- royal_chef
- royal_ghost_evolution
- royal_giant
- royal_hog_evolution
- royal_recruit_evolution
- royal_giant_evolution
- skeleton
- skeleton_army_evolution
- skeleton_balloon
- skeleton_balloon_evolution
- skeleton_dragon
- skeleton_evolution
- skeleton_warrior
- spell_goblin_barrel_evolution
- spell_snowball_evolution
- three_musketeers
- valkyrie
- valkyrie_evolution
- wall_breakers_evolution
- witch
- witch_evolution
- wizard
- wizard_evolution
- archer_queen
- arrows
- barbarian_barrel
- battle_healer
- clone
- earthquake
- electro_dragon
- electro_giant
- electro_spirit
- elite_barbarian
- elixir_golem
- fireball
- fisherman
- freeze
- giant_snowball
- goblin_ball
- goblin_barrel
- goblin_brawler
- goblin_cage
- goblin_giant
- golden_knight
- graveyard
- heal_spirit
- inferno_dragon
- lightning
- little_prince
- log
- magic_archer
- mighty_miner
- monk
- mother_witch
- phoenix_big
- phoenix_egg
- phoenix_small
- poison
- rage
- ram_rider
- rascal_boy
- rascal_girl
- rocket
- royal_delivery
- royal_hog
- royal_recruit
- skeleton_king
- skeleton_king_skill
- sparky
- tornado
- wall_breaker
- zap
- zappy
