"""
YOLO Training Script for Synthetic Clash Royale Dataset

This script trains a YOLO model on the synthetic dataset generated by
build_synthetic_dataset.py. It's designed to work with the comprehensive
sprite-based dataset that includes ally/enemy variants for all troops.

Usage:
    python train_yolo_synthetic.py [options]

Options:
    --data: Path to data.yaml file (default: auto-detect)
    --model: Base YOLO model to use (default: yolo11l.pt)
    --epochs: Number of training epochs (default: 150)
    --imgsz: Training image size (default: 640)
    --batch: Batch size (default: auto)
    --device: Training device (default: auto)
    --resume: Resume from checkpoint (default: False)
"""

import argparse
import os
import sys
from pathlib import Path
from datetime import datetime
import copy
import shutil

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from ultralytics import YOLO
    import torch
    import yaml
except ImportError as e:
    print(f"Missing required package: {e}")
    print("Please install requirements: pip install ultralytics torch pyyaml")
    sys.exit(1)


def find_synthetic_dataset() -> Path:
    """List dataset subfolders under repo dataset/ and ask user which one to use.

    Behavior:
    - If --data provided, that path is used (handled in caller).
    - Otherwise this function lists immediate subdirectories of repo/dataset/,
      shows which contain data.yaml, and prompts the user to choose one.
    - In non-interactive environments (no TTY) it will:
       1) prefer "synthetic_dataset" if present,
       2) else pick the first subfolder that contains data.yaml,
       3) else return None.
    """
    repo_dataset = Path(__file__).parent.parent / "dataset"
    if not repo_dataset.exists():
        return None

    # Gather immediate subdirectories and check for data.yaml
    candidates = []
    for p in sorted([d for d in repo_dataset.iterdir() if d.is_dir()]):
        data_yaml = p / "data.yaml"
        if data_yaml.exists():
            candidates.append((p.name, data_yaml))
        else:
            # also accept nested common names (e.g., dataset/synthetic_dataset/*/data.yaml)
            nested = list(p.rglob("data.yaml"))
            if nested:
                # pick the first nested data.yaml and record relative folder
                candidates.append((p.name + " (nested)", nested[0]))

    # If there is a top-level data.yaml directly under dataset/, prefer it if no other prompt
    top_level = repo_dataset / "data.yaml"
    if top_level.exists():
        candidates.insert(0, ("dataset (top-level)", top_level))

    if not candidates:
        return None

    # If running non-interactively, choose sensible default
    if not sys.stdin.isatty():
        # prefer exact 'synthetic_dataset' folder
        for name, path in candidates:
            if name.startswith("synthetic_dataset"):
                return path
        # else return first candidate
        return candidates[0][1]

    # Interactive selection
    print("\nFound the following dataset folders under ./dataset/:")
    for i, (name, path) in enumerate(candidates):
        print(f"  [{i}] {name} -> {path}")
    print("  [q] Quit")

    # Default selection: pick 'synthetic_dataset' if available
    default_idx = None
    for i, (name, _) in enumerate(candidates):
        if name.startswith("synthetic_dataset"):
            default_idx = i
            break

    while True:
        prompt = "Select dataset index"
        if default_idx is not None:
            prompt += f" (default {default_idx})"
        prompt += ": "
        choice = input(prompt).strip()
        if choice == "" and default_idx is not None:
            return candidates[default_idx][1]
        if choice.lower() in {"q", "quit", "exit"}:
            return None
        if choice.isdigit():
            idx = int(choice)
            if 0 <= idx < len(candidates):
                return candidates[idx][1]
        print("Invalid selection, try again.")


def print_dataset_info(data_yaml_path: Path) -> dict:
    """Print information about the dataset."""
    with open(data_yaml_path, "r") as f:
        data = yaml.safe_load(f)

    print("\n" + "=" * 60)
    print("📊 DATASET INFORMATION")
    print("=" * 60)
    print(f"📁 Data path: {data.get('path', 'Not specified')}")
    print(f"📈 Number of classes: {data.get('nc', 'Unknown')}")
    print(f"🏋️ Train path: {data.get('train', 'Not specified')}")
    print(f"✅ Val path: {data.get('val', 'Not specified')}")
    print(f"🧪 Test path: {data.get('test', 'Not specified')}")

    # Print class summary
    names = data.get("names", [])
    if names:
        ally_classes = [n for n in names if n.startswith("ally_")]
        enemy_classes = [n for n in names if n.startswith("enemy_")]
        other_classes = [
            n for n in names if not n.startswith("ally_") and not n.startswith("enemy_")
        ]

        print(f"\n📋 Class breakdown:")
        print(f"   • Ally troops/buildings: {len(ally_classes)}")
        print(f"   • Enemy troops/buildings: {len(enemy_classes)}")
        print(f"   • Other (UI, effects): {len(other_classes)}")

    print("=" * 60 + "\n")
    return data


def get_gpu_info() -> dict:
    """Get information about available GPU(s)."""
    info = {
        "cuda_available": torch.cuda.is_available(),
        "device_count": 0,
        "devices": [],
    }

    if torch.cuda.is_available():
        info["device_count"] = torch.cuda.device_count()
        for i in range(info["device_count"]):
            props = torch.cuda.get_device_properties(i)
            info["devices"].append(
                {
                    "name": props.name,
                    "memory_gb": props.total_memory / (1024**3),
                    "compute_capability": f"{props.major}.{props.minor}",
                }
            )

    return info


def print_system_info():
    """Print system and GPU information."""
    print("\n" + "=" * 60)
    print("🖥️ SYSTEM INFORMATION")
    print("=" * 60)
    print(f"⏰ Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"🐍 Python: {sys.version.split()[0]}")
    print(f"🔥 PyTorch: {torch.__version__}")

    gpu_info = get_gpu_info()
    if gpu_info["cuda_available"]:
        print(f"🎮 CUDA Available: Yes")
        for i, device in enumerate(gpu_info["devices"]):
            print(f"   GPU {i}: {device['name']}")
            print(f"   Memory: {device['memory_gb']:.2f} GB")
            print(f"   Compute: {device['compute_capability']}")
    else:
        print("⚠️ CUDA Available: No - Training will be slow on CPU!")

    print("=" * 60 + "\n")


def calculate_batch_size(gpu_memory_gb: float, img_size: int) -> int:
    """Calculate optimal batch size based on GPU memory and image size."""

    if img_size <= 640:
        base_batch = 16
        memory_per_batch = 0.25  # GB per image
    elif img_size <= 960:
        base_batch = 8
        memory_per_batch = 0.5
    else:
        base_batch = 4
        memory_per_batch = 1.0

    # Leave 2GB headroom for model and overhead
    available = gpu_memory_gb - 2.0
    estimated_batch = int(available / memory_per_batch)

    # Clamp to reasonable values
    return max(4, min(32, estimated_batch))


def train(args):
    """Run the training process."""
    # Print system info
    print_system_info()

    # Find dataset
    if args.data:
        data_yaml = Path(args.data)
    else:
        data_yaml = find_synthetic_dataset()

    if data_yaml is None or not data_yaml.exists():
        print("❌ Error: Could not find data.yaml for synthetic dataset!")
        print("Please specify the path with --data argument")
        print("Or run build_synthetic_dataset.py first to generate the dataset")
        sys.exit(1)

    # Print dataset info
    data_config = print_dataset_info(data_yaml)

    # Load model
    print(f"📦 Loading model: {args.model}")
    model = YOLO(args.model)

    # Determine device
    if args.device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"
    else:
        device = str(args.device)

    # Determine batch size
    batch_size = args.batch
    if batch_size == -1:  # Auto
        gpu_info = get_gpu_info()
        if gpu_info["cuda_available"] and gpu_info["devices"]:
            gpu_mem = gpu_info["devices"][0]["memory_gb"]
            batch_size = calculate_batch_size(gpu_mem, args.imgsz)
            print(f"🔄 Auto batch size: {batch_size} (based on {gpu_mem:.1f}GB GPU)")
        else:
            batch_size = 4
            print(f"🔄 Default batch size: {batch_size} (CPU mode)")

    # Base training args (will be copied/modified per stage)
    base_train_args = {
        "data": str(data_yaml),
        "epochs": args.epochs,
        "batch": batch_size,
        "imgsz": args.imgsz,
        "device": device,
        "workers": args.workers,
        "project": args.project,
        "name": f"train_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
        "exist_ok": args.exist_ok,
        "save": True,
        "save_period": args.save_period,
        "val": True,
        "plots": True,
        "verbose": True,
        "seed": args.seed,
        "deterministic": args.deterministic,
        "single_cls": False,
        "rect": args.rect,
        "cos_lr": True,
        "close_mosaic": 10,
        "resume": False,
        "amp": True,
        "cache": args.cache,
        # augmentation/loss/optim params
        "optimizer": "SGD",
        "lr0": args.lr0,
        "lrf": args.lrf,
        "momentum": args.momentum,
        "weight_decay": args.weight_decay,
        "warmup_epochs": args.warmup_epochs,
        "warmup_momentum": args.warmup_momentum,
        "warmup_bias_lr": args.warmup_bias_lr,
        "hsv_h": args.hsv_h,
        "hsv_s": args.hsv_s,
        "hsv_v": args.hsv_v,
        "degrees": 5.0,
        "translate": 0.1,
        "scale": 0.35,
        "fliplr": 0.5,
        "flipud": 0.0,
        "mosaic": 1.0,
        "mixup": 0.1,
        "copy_paste": 0.1,
    }
    # allow resuming/from-weights provided by CLI
    if getattr(args, "resume", False):
        base_train_args["resume"] = True

    print("\n" + "=" * 60)
    print("🚀 TRAINING CONFIGURATION")
    print("=" * 60)
    print(f"📁 Dataset: {data_yaml}")
    print(f"🔧 Model: {args.model}")
    print(f"📐 Target image size: {args.imgsz}")
    print(f"📦 Batch size: {batch_size}")
    print(f"🔄 Epochs: {args.epochs}")
    print(f"💻 Device: {device}")
    print(f"👥 Workers: {args.workers}")
    print(f"📁 Output project: {args.project}")
    print("=" * 60 + "\n")

    # Two-stage training option: pretrain at lower resolution then fine-tune at target
    if args.two_stage:
        stage1_imgsz = args.stage1_imgsz
        stage1_epochs = args.stage1_epochs
        print(
            f"⚙️ Two-stage training enabled: stage1 {stage1_imgsz}px x {stage1_epochs} epochs -> stage2 {args.imgsz}px x {args.epochs - stage1_epochs} epochs"
        )

        # Stage 1
        stage1_args = copy.deepcopy(base_train_args)
        stage1_args["imgsz"] = stage1_imgsz
        stage1_args["epochs"] = stage1_epochs
        stage1_args["name"] = f"{stage1_args['name']}_stage1"
        stage1_args["rect"] = False  # keep stage1 rectangular off for speed
        print("▶️ Starting stage 1 (fast pretrain)...")
        res1 = model.train(**stage1_args)

        # Find the best weight from stage1
        best_w = Path(res1.save_dir) / "weights" / "best.pt"
        if not best_w.exists():
            # fallback to last.pt
            best_w = Path(res1.save_dir) / "weights" / "last.pt"
        if not best_w.exists():
            print(
                "⚠️ Could not find stage1 weights to resume from; aborting two-stage flow."
            )
            return

        # Stage 2: fine-tune at target size
        stage2_args = copy.deepcopy(base_train_args)
        stage2_args["imgsz"] = args.imgsz
        stage2_args["epochs"] = max(1, args.epochs - stage1_epochs)
        stage2_args["name"] = f"{stage2_args['name']}_stage2"
        stage2_args["rect"] = True  # enable rect mode for final fine-tune
        print("▶️ Starting stage 2 (fine-tune)...")
        # load weights into model
        model = YOLO(str(best_w))
        res2 = model.train(**stage2_args)

        final_res = res2

    else:
        # Single-stage training
        single_args = copy.deepcopy(base_train_args)
        single_args["rect"] = args.rect
        single_args["imgsz"] = args.imgsz
        single_args["epochs"] = args.epochs
        single_args["name"] = single_args["name"] + "_single"
        if args.resume:
            single_args["resume"] = True
        print("▶️ Starting single-stage training...")
        final_res = model.train(**single_args)

    # Print results
    print("\n" + "=" * 60)
    print("✅ TRAINING COMPLETE")
    print("=" * 60)
    print(f"📁 Results saved to: {final_res.save_dir}")
    print(f"🏆 Best model: {final_res.save_dir}/weights/best.pt")
    print("=" * 60 + "\n")

    return final_res


def validate(args):
    """Run validation on the trained model."""
    print("🔍 Running validation...")

    if not args.weights:
        print("❌ Error: Please specify model weights with --weights")
        sys.exit(1)

    model = YOLO(args.weights)

    # Find dataset
    if args.data:
        data_yaml = Path(args.data)
    else:
        data_yaml = find_synthetic_dataset()

    if data_yaml is None or not data_yaml.exists():
        print("❌ Error: Could not find data.yaml")
        sys.exit(1)

    results = model.val(
        data=str(data_yaml),
        imgsz=args.imgsz,
        batch=args.batch if args.batch != -1 else 16,
        device=args.device if args.device != "auto" else 0,
        workers=args.workers,
        split="test" if args.test else "val",
        save_json=True,
        plots=True,
    )

    print("\n📊 Validation Results:")
    print(f"   • mAP50: {results.box.map50:.4f}")
    print(f"   • mAP50-95: {results.box.map:.4f}")

    return results


def main():
    parser = argparse.ArgumentParser(
        description="Train YOLO on Synthetic Clash Royale Dataset"
    )

    # Mode
    parser.add_argument(
        "--mode",
        type=str,
        default="train",
        choices=["train", "val"],
        help="Training or validation mode",
    )

    # Dataset
    parser.add_argument("--data", type=str, default=None, help="Path to data.yaml file")

    # Model
    parser.add_argument(
        "--model",
        type=str,
        default="yolo11l.pt",
        help="Base YOLO model (yolo11s.pt, yolo11m.pt, etc.)",
    )
    parser.add_argument(
        "--weights",
        type=str,
        default=None,
        help="Path to pretrained weights for resume/validation",
    )
    parser.add_argument(
        "--resume", action="store_true", help="Resume training from checkpoint"
    )

    # Training params
    parser.add_argument(
        "--epochs",
        type=int,
        default=150,
        help="Number of training epochs (final total)",
    )
    parser.add_argument(
        "--imgsz", type=int, default=640, help="Training image long-edge size (px)"
    )
    parser.add_argument(
        "--batch", type=int, default=-1, help="Batch size (-1 for auto)"
    )

    # Two-stage fine-tune
    parser.add_argument(
        "--two-stage",
        action="store_true",
        help="Enable two-stage (pretrain low-res -> fine-tune high-res)",
    )
    parser.add_argument(
        "--stage1-imgsz", type=int, default=640, help="Stage1 image size"
    )
    parser.add_argument("--stage1-epochs", type=int, default=40, help="Stage1 epochs")

    # Hardware
    parser.add_argument(
        "--device", type=str, default="auto", help="Training device (auto, 0, 1, cpu)"
    )
    parser.add_argument(
        "--workers", type=int, default=8, help="Number of data loader workers"
    )
    parser.add_argument(
        "--cache",
        type=str,
        default=False,
        help="Cache images (False, True, 'ram', 'disk')",
    )

    # Misc
    parser.add_argument(
        "--project", type=str, default="runs/synthetic", help="Ultralytics project path"
    )
    parser.add_argument(
        "--exist_ok", action="store_true", help="Overwrite existing run"
    )
    parser.add_argument(
        "--save_period", type=int, default=3, help="Save period (epochs)"
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--deterministic", action="store_true")
    parser.add_argument(
        "--rect",
        action="store_true",
        default=False,
        help="Enable rect training for final stage",
    )
    parser.add_argument(
        "--test", action="store_true", help="Use test split for validation"
    )

    # Additional optimizer/augmentation params (exposed for easy tuning)
    parser.add_argument("--lr0", type=float, default=0.001)
    parser.add_argument("--lrf", type=float, default=0.01)
    parser.add_argument("--momentum", type=float, default=0.937)
    parser.add_argument("--weight_decay", type=float, default=0.0005)
    parser.add_argument("--warmup_epochs", type=float, default=3.0)
    parser.add_argument("--warmup_momentum", type=float, default=0.8)
    parser.add_argument("--warmup_bias_lr", type=float, default=0.1)
    parser.add_argument("--hsv_h", type=float, default=0.015)
    parser.add_argument("--hsv_s", type=float, default=0.7)
    parser.add_argument("--hsv_v", type=float, default=0.4)

    args = parser.parse_args()

    print("\n" + "=" * 60)
    print("🎮 CLASH ROYALE AI - SYNTHETIC DATASET TRAINING")
    print("=" * 60)

    if args.mode == "train":
        train(args)
    else:
        validate(args)


if __name__ == "__main__":
    main()
