"""M4 tests: fixed-scenario runner + trace contract + diff tool (M4.1).

Run:  python3 -m gpusim.tests.test_m4

Executes the full 5-scenario, 75 s batch twice (determinism check, ~15 s) and
asserts on the traces in-memory — not on the committed files under
fidelity/m4_traces/ (those are regenerated by `fidelity/m4_scenarios.py run`
whenever behaviour changes; see docs/M4_TRACE_FORMAT.md).

The tick-exact constants below are the executable spec of the ported mechanics
(attack cadence, windup/load time, projectile flight, tower fire, spell crown
%) — if a change moves them, the change must be intentional and the constants
updated together with the regenerated traces.
"""
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from fidelity import m4_scenarios as m4  # noqa: E402

_CACHE: dict = {}
REQUIRED_KEYS = {"i", "t", "el", "th", "ta", "cr", "go", "w"}


def _runs():
    if "a" not in _CACHE:
        _CACHE["a"] = m4.run_scenarios()
        _CACHE["b"] = m4.run_scenarios()
    return _CACHE["a"], _CACHE["b"]


def _unit_events(recs, side, card):
    """[(tick, hp_delta)] for every hp decrease of the first matching unit."""
    prev, events = None, []
    for r in recs:
        u = [x for x in r.get("u", []) if x["s"] == side and x["c"] == card]
        hp = u[0]["hp"] if u else None
        if prev is not None and hp is not None and hp < prev - 1e-9:
            events.append((r["i"], round(prev - hp, 2)))
        prev = hp
    return events


def _present(recs, side, card):
    return [r["i"] for r in recs if any(x["s"] == side and x["c"] == card for x in r.get("u", []))]


def _tower_events(recs, slot):
    th = [r["th"][slot] for r in recs]
    return [(i, round(th[i - 1] - th[i], 2)) for i in range(1, len(th)) if th[i] < th[i - 1] - 1e-9]


def test_trace_contract():
    runs, _ = _runs()
    for sc in m4.SCENARIOS:
        recs = runs[sc.name]["records"]
        assert len(recs) == m4.DURATION_TICKS + 1, f"{sc.name}: {len(recs)} records"
        assert all(REQUIRED_KEYS <= set(r) for r in recs)
        first, last = recs[0], recs[-1]
        assert first["i"] == 0 and first["t"] == 0.0
        assert first["el"] == [5.0, 5.0]
        assert first["th"] == [4824.0, 3052.0, 3052.0, 4824.0, 3052.0, 3052.0]
        assert first["ta"] == [1] * 6 and first["cr"] == [0, 0]
        assert last["i"] == m4.DURATION_TICKS and last["t"] == 75.0
        ts = [r["t"] for r in recs]
        assert all(b > a for a, b in zip(ts, ts[1:])), "time must be strictly increasing"
        for r in recs:
            assert len(r["th"]) == 6 and len(r["ta"]) == 6 and len(r["el"]) == 2
            for u in r.get("u", []):
                assert set(u) == {"s", "c", "x", "y", "hp"}
                assert u["c"] == u["c"].lower()
        for r in recs:  # unit order contract: sorted by (side, x, y)
            us = r.get("u", [])
            assert us == sorted(us, key=lambda u: (u["s"], u["x"], u["y"]))
        # HP floors at 0 (Java Health.takeDamage: current -= min(damage, current))
        assert min(min(r["th"]) for r in recs) >= 0.0
        assert min((u["hp"] for r in recs for u in r.get("u", [])), default=0.0) >= 0.0


def test_determinism_two_runs_identical():
    a, b = _runs()
    for sc in m4.SCENARIOS:
        assert a[sc.name]["text"] == b[sc.name]["text"], f"{sc.name}: runs differ"


def test_duel_knight_mirror_mutual_ko():
    runs, _ = _runs()
    recs = runs["duel_knight"]["records"]
    # Java sync timeline: 25-tick attack cycles, first hit at t=6.45 — verified
    # against the java_patched reference trace (byte-identical at this revision)
    cadence = [129, 154, 179, 204, 229, 254, 279, 304]
    for side in (0, 1):
        ev = _unit_events(recs, side, "knight")
        assert [t for t, _ in ev] == cadence, f"side {side}: {ev}"
        assert all(abs(d - 202.0) < 0.05 for _, d in ev), f"side {side} damage values"
    # identical cadence -> both knights die on the same tick (mutual KO at t=16.45)
    for side in (0, 1):
        present = _present(recs, side, "knight")
        assert present[0] == 41 and present[-1] == 328, f"side {side}: {present[0]}..{present[-1]}"
    # the duel happened mid-bridge, no tower was touched
    assert recs[-1]["th"] == recs[0]["th"] and recs[-1]["cr"] == [0, 0]


def test_duel_musketeer_projectiles_and_tower_trade():
    runs, _ = _runs()
    recs = runs["duel_musketeer"]["records"]
    ev = _unit_events(recs, 1, "knight")
    proj = [(t, d) for t, d in ev if abs(d - 263.0) < 0.1]
    tower_fire = [(t, d) for t, d in ev if abs(d - 109.0) < 0.1]
    assert [t for t, _ in proj] == [105, 123, 142, 161, 180], f"projectile hits: {proj}"
    assert [t for t, _ in tower_fire] == [176, 193], f"blue-tower hits: {tower_fire}"
    assert _present(recs, 1, "knight")[-1] == 199  # dead at 200 (t=10.00)
    # musketeer survives the duel, then lands exactly 5 hits on red princess-R
    tev = _tower_events(recs, 5)
    assert [t for t, _ in tev] == [346, 366, 386, 406, 426], f"tower hits: {tev}"
    assert all(abs(d - 263.0) < 0.1 for _, d in tev)
    assert abs(recs[-1]["th"][5] - (3052.0 - 5 * 263.0)) < 0.05
    assert _present(recs, 0, "musketeer")[-1] == 420  # dead at 421 (t=21.05)
    assert recs[-1]["th"][:3] == recs[0]["th"][:3], "blue towers must be untouched"


def test_tower_press_melee_vs_tower():
    runs, _ = _runs()
    recs = runs["tower_press"]["records"]
    tev = _tower_events(recs, 4)  # red left princess tower
    assert [t for t, _ in tev] == [238, 263, 288, 313, 338, 363, 388], f"tower hits: {tev}"
    assert all(abs(d - 202.0) < 0.05 for _, d in tev)
    assert abs(recs[-1]["th"][4] - (3052.0 - 7 * 202.0)) < 0.05
    ev = _unit_events(recs, 0, "knight")
    assert len(ev) == 16 and all(abs(d - 109.0) < 0.05 for _, d in ev), "tower fire only"
    assert _present(recs, 0, "knight")[-1] == 391  # dead at 392 (t=19.60)
    # 3 elixir spent on the knight between tick 20 and 21
    assert abs((recs[20]["el"][0] - recs[21]["el"][0]) - (3.0 - 0.017857)) < 1e-3
    assert recs[-1]["th"][:3] == recs[0]["th"][:3]


def test_spell_hit_fireball_crown_damage():
    runs, _ = _runs()
    recs = runs["spell_hit"]["records"]
    # deploy at tick 60 (red knight), fireball cast between tick 80 and 81.
    # M3.4 flight: the cast fires after the 1.0 s sync, flies from the crown
    # tower at 10 tiles/s and detonates at tick 142 (t=7.10) — Java-verified:
    # the java_patched spell_hit trace matches byte-for-byte.
    assert _present(recs, 1, "knight")[0] == 81
    hp141 = [x["hp"] for x in recs[141]["u"] if x["c"] == "knight"][0]
    hp142 = [x["hp"] for x in recs[142]["u"] if x["c"] == "knight"][0]
    assert abs(hp141 - 1766.0) < 0.05 and abs((hp141 - hp142) - 688.0) < 0.1  # floor(269 * 2.56)
    assert abs((recs[141]["th"][5] - recs[142]["th"][5]) - 206.0) < 0.1      # floor(688 * 0.30)
    assert abs((recs[80]["el"][0] - recs[81]["el"][0]) - (4.0 - 0.017857)) < 1e-3
    # knight survives and marches the full lane; two melee hits on blue princess-R
    tev = _tower_events(recs, 2)
    assert [t for t, _ in tev] == [397, 422], f"tower hits: {tev}"
    assert all(abs(d - 202.0) < 0.05 for _, d in tev)
    assert _present(recs, 1, "knight")[-1] == 431  # dead at 432 (t=21.60)


def test_push_left_tower_falls_and_hp_floor():
    runs, _ = _runs()
    recs = runs["push_left"]["records"]
    # red left princess tower: knight damage, then musketeer finishes; hp floors at 0
    first_dead = next(r["i"] for r in recs if r["ta"][4] == 0)
    assert first_dead == 450, f"tower should fall at tick 450 (t=22.50), got {first_dead}"
    assert recs[first_dead]["th"][4] == 0.0 and recs[first_dead]["cr"] == [1, 0]
    assert all(r["th"][4] >= 0.0 for r in recs), "no negative tower hp anywhere (overkill clamp)"
    # both attackers die; blue keeps the crown
    assert _present(recs, 0, "knight")[-1] == 391 and _present(recs, 0, "musketeer")[-1] == 628
    assert recs[-1]["cr"] == [1, 0] and recs[-1]["w"] == -1


def test_log_roll_spell_as_deploy_chain():
    """M3.6 (log_roll): The Log deploys at the cast point; the rolling
    sub-projectile hits the red knight once (scaleCard(105) = 268) with
    directional pushback (35 game units/tick for 10 ticks), never touches the
    flying minions, and lands 15 % crown damage (40) on the red left princess.
    Verified byte-identical against the java_patched trace (see
    reports/m4_fidelity_report.md)."""
    runs, _ = _runs()
    recs = runs["log_roll"]["records"]
    assert _present(recs, 1, "knight")[0] == 101  # red deploy at tick 80 -> 101
    ev = _unit_events(recs, 1, "knight")
    assert ev[0] == (115, 268.0), f"log hit: {ev[0]}"
    # knockback: the hit tick drops y by 0.035 tiles for 10 ticks (700/1.0 * 0.5)
    ky = {r["i"]: [u["y"] for u in r.get("u", [])
                   if u["s"] == 1 and u["c"] == "knight"][0] for r in recs if
          any(u["s"] == 1 and u["c"] == "knight" for u in r.get("u", []))}
    assert ky[114] == 12.5 and ky[115] == 12.465 and ky[124] == 12.15
    assert ky[125] == 12.2, "walking resumes after the knockback ends"
    # air immunity: the MegaMinion's only damage is blue tower fire (109)
    mev = _unit_events(recs, 1, "megaminion")
    assert mev and all(abs(d - 109.0) < 0.05 and t >= 236 for t, d in mev), mev
    # crown-tower damage: exactly one 40-damage event on the red left princess
    tev = _tower_events(recs, 4)
    assert tev == [(147, 40.0)], tev


def test_compare_tool_detects_first_divergence():
    runs, _ = _runs()
    text = runs["duel_knight"]["text"]
    with tempfile.TemporaryDirectory() as td:
        p1 = Path(td) / "a.jsonl"
        p2 = Path(td) / "b.jsonl"
        p1.write_text(text)
        p2.write_text(text)
        res = m4.compare_traces(p1, p2, tol=0.0)
        assert res["first_divergence_tick"] is None, res
        recs = [json.loads(line) for line in text.splitlines()]
        recs[42]["th"][0] += 5.0
        p2.write_text("".join(json.dumps(r, separators=(",", ":")) + "\n" for r in recs))
        res = m4.compare_traces(p1, p2, tol=0.0)
        assert res["first_divergence_tick"] == 42, res
        assert res["max_abs_diff"]["th"] == 5.0, res
        # within tolerance -> no divergence flagged
        res = m4.compare_traces(p1, p2, tol=5.0)
        assert res["first_divergence_tick"] is None, res


if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    for fn in fns:
        fn()
        print(f"PASS {fn.__name__}")
    print(f"\n{len(fns)} tests passed")
