"""M4 tests: fixed-scenario runner + trace contract + diff tool (M4.1).

Run:  python3 -m gpusim.tests.test_m4

Executes the full 5-scenario, 75 s batch twice (determinism check, ~15 s) and
asserts on the traces in-memory — not on the committed files under
fidelity/m4_traces/ (those are regenerated by `fidelity/m4_scenarios.py run`
whenever behaviour changes; see docs/M4_TRACE_FORMAT.md).

The tick-exact constants below are the executable spec of the ported mechanics
(attack cadence, windup/load time, projectile flight, tower fire, spell crown
%) — if a change moves them, the change must be intentional and the constants
updated together with the regenerated traces.
"""
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from fidelity import m4_scenarios as m4  # noqa: E402

_CACHE: dict = {}
REQUIRED_KEYS = {"i", "t", "el", "th", "ta", "cr", "go", "w"}


def _runs():
    if "a" not in _CACHE:
        _CACHE["a"] = m4.run_scenarios()
        _CACHE["b"] = m4.run_scenarios()
    return _CACHE["a"], _CACHE["b"]


def _unit_events(recs, side, card):
    """[(tick, hp_delta)] for every hp decrease of the first matching unit."""
    prev, events = None, []
    for r in recs:
        u = [x for x in r.get("u", []) if x["s"] == side and x["c"] == card]
        hp = u[0]["hp"] if u else None
        if prev is not None and hp is not None and hp < prev - 1e-9:
            events.append((r["i"], round(prev - hp, 2)))
        prev = hp
    return events


def _present(recs, side, card):
    return [r["i"] for r in recs if any(x["s"] == side and x["c"] == card for x in r.get("u", []))]


def _tower_events(recs, slot):
    th = [r["th"][slot] for r in recs]
    return [(i, round(th[i - 1] - th[i], 2)) for i in range(1, len(th)) if th[i] < th[i - 1] - 1e-9]


def test_trace_contract():
    runs, _ = _runs()
    for sc in m4.SCENARIOS:
        recs = runs[sc.name]["records"]
        assert len(recs) == m4.DURATION_TICKS + 1, f"{sc.name}: {len(recs)} records"
        assert all(REQUIRED_KEYS <= set(r) for r in recs)
        first, last = recs[0], recs[-1]
        assert first["i"] == 0 and first["t"] == 0.0
        assert first["el"] == [5.0, 5.0]
        assert first["th"] == [4824.0, 3052.0, 3052.0, 4824.0, 3052.0, 3052.0]
        assert first["ta"] == [1] * 6 and first["cr"] == [0, 0]
        assert last["i"] == m4.DURATION_TICKS and last["t"] == 75.0
        ts = [r["t"] for r in recs]
        assert all(b > a for a, b in zip(ts, ts[1:])), "time must be strictly increasing"
        for r in recs:
            assert len(r["th"]) == 6 and len(r["ta"]) == 6 and len(r["el"]) == 2
            for u in r.get("u", []):
                assert set(u) == {"s", "c", "x", "y", "hp"}
                assert u["c"] == u["c"].lower()
        for r in recs:  # unit order contract: sorted by (side, x, y)
            us = r.get("u", [])
            assert us == sorted(us, key=lambda u: (u["s"], u["x"], u["y"]))
        # HP floors at 0 (Java Health.takeDamage: current -= min(damage, current))
        assert min(min(r["th"]) for r in recs) >= 0.0
        assert min((u["hp"] for r in recs for u in r.get("u", [])), default=0.0) >= 0.0


def test_determinism_two_runs_identical():
    a, b = _runs()
    for sc in m4.SCENARIOS:
        assert a[sc.name]["text"] == b[sc.name]["text"], f"{sc.name}: runs differ"


def test_duel_knight_mirror_mutual_ko():
    runs, _ = _runs()
    recs = runs["duel_knight"]["records"]
    cadence = [109, 133, 157, 181, 205, 229, 253, 277]  # 1.2 s attack cooldown
    for side in (0, 1):
        ev = _unit_events(recs, side, "knight")
        assert [t for t, _ in ev] == cadence, f"side {side}: {ev}"
        assert all(abs(d - 202.21) < 0.05 for _, d in ev), f"side {side} damage values"
    # identical cadence -> both knights die on the same tick (t=15.05)
    for side in (0, 1):
        present = _present(recs, side, "knight")
        assert present[0] == 21 and present[-1] == 300, f"side {side}: {present[0]}..{present[-1]}"
    # the duel happened mid-bridge, no tower was touched
    assert recs[-1]["th"] == recs[0]["th"] and recs[-1]["cr"] == [0, 0]


def test_duel_musketeer_projectiles_and_tower_trade():
    runs, _ = _runs()
    recs = runs["duel_musketeer"]["records"]
    ev = _unit_events(recs, 1, "knight")
    proj = [(t, d) for t, d in ev if abs(d - 263.64) < 0.1]
    tower_fire = [(t, d) for t, d in ev if abs(d - 109.0) < 0.1]
    assert [t for t, _ in proj] == [80, 99, 118, 137, 156], f"projectile hits: {proj}"
    assert [t for t, _ in tower_fire] == [130, 146, 162], f"blue-tower hits: {tower_fire}"
    assert _present(recs, 1, "knight")[-1] == 175  # dead at 176 (t=8.80)
    # musketeer survives the duel, then lands exactly 3 hits on red princess-R
    tev = _tower_events(recs, 5)
    assert [t for t, _ in tev] == [320, 340, 360], f"tower hits: {tev}"
    assert all(abs(d - 263.64) < 0.1 for _, d in tev)
    assert abs(recs[-1]["th"][5] - (3052.0 - 3 * 263.64)) < 0.05
    assert _present(recs, 0, "musketeer")[-1] == 362  # dead at 363 (t=18.15)
    assert recs[-1]["th"][:3] == recs[0]["th"][:3], "blue towers must be untouched"


def test_tower_press_melee_vs_tower():
    runs, _ = _runs()
    recs = runs["tower_press"]["records"]
    tev = _tower_events(recs, 4)  # red left princess tower
    assert [t for t, _ in tev] == [221, 245, 269, 293, 317], f"tower hits: {tev}"
    assert all(abs(d - 202.21) < 0.05 for _, d in tev)
    assert abs(recs[-1]["th"][4] - (3052.0 - 5 * 202.21)) < 0.05
    ev = _unit_events(recs, 0, "knight")
    assert len(ev) == 16 and all(abs(d - 109.0) < 0.05 for _, d in ev), "tower fire only"
    assert _present(recs, 0, "knight")[-1] == 336  # dead at 337 (t=16.85)
    # 3 elixir spent on the knight between tick 20 and 21
    assert abs((recs[20]["el"][0] - recs[21]["el"][0]) - (3.0 - 0.017857)) < 1e-3
    assert recs[-1]["th"][:3] == recs[0]["th"][:3]


def test_spell_hit_fireball_crown_damage():
    runs, _ = _runs()
    recs = runs["spell_hit"]["records"]
    # deploy at tick 60 (red knight), fireball cast between tick 80 and 81.
    # (M3.3 instant-cast behaviour; when M3.4 spell flight time lands, the
    # impact shifts a few ticks and these constants must move with it.)
    assert _present(recs, 1, "knight")[0] == 61
    hp80 = [x["hp"] for x in recs[80]["u"] if x["c"] == "knight"][0]
    hp81 = [x["hp"] for x in recs[81]["u"] if x["c"] == "knight"][0]
    assert abs(hp80 - 1766.12) < 0.05 and abs((hp80 - hp81) - 688.53) < 0.1  # 269 * 2.5596
    assert abs((recs[80]["th"][5] - recs[81]["th"][5]) - 206.56) < 0.1      # x0.30 vs towers
    assert abs((recs[80]["el"][0] - recs[81]["el"][0]) - (4.0 - 0.017857)) < 1e-3
    # knight survives and marches the full lane; one melee hit on blue princess-R
    tev = _tower_events(recs, 2)
    assert [t for t, _ in tev] == [390] and abs(tev[0][1] - 202.21) < 0.05
    assert _present(recs, 1, "knight")[-1] == 393  # dead at 394 (t=19.70)


def test_push_left_tower_falls_and_hp_floor():
    runs, _ = _runs()
    recs = runs["push_left"]["records"]
    # red left princess tower: knight damage, then musketeer finishes; hp floors at 0
    first_dead = next(r["i"] for r in recs if r["ta"][4] == 0)
    assert first_dead == 444, f"tower should fall at tick 444 (t=22.20), got {first_dead}"
    assert recs[first_dead]["th"][4] == 0.0 and recs[first_dead]["cr"] == [1, 0]
    assert all(r["th"][4] >= 0.0 for r in recs), "no negative tower hp anywhere (overkill clamp)"
    # both attackers die; blue keeps the crown
    assert _present(recs, 0, "knight")[-1] == 336 and _present(recs, 0, "musketeer")[-1] == 522
    assert recs[-1]["cr"] == [1, 0] and recs[-1]["w"] == -1


def test_compare_tool_detects_first_divergence():
    runs, _ = _runs()
    text = runs["duel_knight"]["text"]
    with tempfile.TemporaryDirectory() as td:
        p1 = Path(td) / "a.jsonl"
        p2 = Path(td) / "b.jsonl"
        p1.write_text(text)
        p2.write_text(text)
        res = m4.compare_traces(p1, p2, tol=0.0)
        assert res["first_divergence_tick"] is None, res
        recs = [json.loads(line) for line in text.splitlines()]
        recs[42]["th"][0] += 5.0
        p2.write_text("".join(json.dumps(r, separators=(",", ":")) + "\n" for r in recs))
        res = m4.compare_traces(p1, p2, tol=0.0)
        assert res["first_divergence_tick"] == 42, res
        assert res["max_abs_diff"]["th"] == 5.0, res
        # within tolerance -> no divergence flagged
        res = m4.compare_traces(p1, p2, tol=5.0)
        assert res["first_divergence_tick"] is None, res


if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    for fn in fns:
        fn()
        print(f"PASS {fn.__name__}")
    print(f"\n{len(fns)} tests passed")
