# policy/offline/card_list.py

elixir2card = {
    -1: ["mirror"],
    1: [
        "electro-spirit",
        "fire-spirit",
        "heal-spirit",
        "ice-spirit",
        "ice-spirit-evolution",
        "skeletons",
        "skeletons-evolution",
    ],
    2: [
        "barbarian-barrel",
        "bats",
        "bats-evolution",
        "berserker",
        "bomber",
        "bomber-evolution",
        "giant-snowball",
        "giant-snowball-evolution",
        "goblin-curse",
        "goblins",
        "ice-golem",
        "rage",
        "spear-goblins",
        "suspicious-bush",
        "the-log",
        "wall-breakers",
        "wall-breakers-evolution",
        "zap",
        "zap-evolution",
    ],
    3: [
        "archers",
        "archers-evolution",
        "arrows",
        "bandit",
        "cannon",
        "cannon-evolution",
        "clone",
        "dart-goblin",
        "dart-goblin-evolution",
        "earthquake",
        "elixir-golem",
        "firecracker",
        "firecracker-evolution",
        "fisherman",
        "goblin-barrel",
        "goblin-barrel-evolution",
        "goblin-gang",
        "guards",
        "ice-wizard",
        "knight",
        "knight-evolution",
        "knight-hero",
        "little-prince",
        "mega-minion",
        "miner",
        "minions",
        "princess",
        "royal-delivery",
        "royal-ghost",
        "royal-ghost-evolution",
        "skeleton-army",
        "skeleton-army-evolution",
        "skeleton-barrel",
        "skeleton-barrel-evolution",
        "tombstone",
        "tornado",
        "vines",
        "void",
    ],
    4: [
        "baby-dragon",
        "baby-dragon-evolution",
        "battle-healer",
        "battle-ram",
        "battle-ram-evolution",
        "bomb-tower",
        "dark-prince",
        "electro-wizard",
        "fireball",
        "flying-machine",
        "freeze",
        "furnace",
        "furnace-evolution",
        "goblin-cage",
        "goblin-cage-evolution",
        "goblin-demolisher",
        "goblin-drill",
        "goblin-drill-evolution",
        "golden-knight",
        "hog-rider",
        "hunter",
        "hunter-evolution",
        "inferno-dragon",
        "inferno-dragon-evolution",
        "lumberjack",
        "lumberjack-evolution",
        "magic-archer",
        "mighty-miner",
        "mini-pekka",
        "mini-pekka-hero",
        "mortar",
        "mortar-evolution",
        "mother-witch",
        "musketeer",
        "musketeer-evolution",
        "musketeer-hero",
        "night-witch",
        "phoenix",
        "poison",
        "rune-giant",
        "skeleton-dragons",
        "skeleton-king",
        "tesla",
        "tesla-evolution",
        "valkyrie",
        "valkyrie-evolution",
        "zappies",
    ],
    5: [
        "archer-queen",
        "balloon",
        "barbarians",
        "barbarians-evolution",
        "bowler",
        "cannon-cart",
        "electro-dragon",
        "electro-dragon-evolution",
        "executioner",
        "executioner-evolution",
        "giant",
        "giant-hero",
        "goblin-hut",
        "goblin-machine",
        "goblinstein",
        "graveyard",
        "inferno-tower",
        "minion-horde",
        "monk",
        "prince",
        "ram-rider",
        "rascals",
        "royal-hogs",
        "royal-hogs-evolution",
        "witch",
        "witch-evolution",
        "wizard",
        "wizard-evolution",
    ],
    6: [
        "barbarian-hut",
        "boss-bandit",
        "elite-barbarians",
        "elixir-collector",
        "giant-skeleton",
        "goblin-giant",
        "goblin-giant-evolution",
        "lightning",
        "rocket",
        "royal-giant",
        "royal-giant-evolution",
        "sparky",
        "spirit-empress",
        "x-bow",
    ],
    7: [
        "electro-giant",
        "lava-hound",
        "mega-knight",
        "mega-knight-evolution",
        "pekka",
        "pekka-evolution",
        "royal-recruits",
        "royal-recruits-evolution",
    ],
    8: ["golem"],
    9: ["three-musketeers"],
    10: [],
}

card2elixir = {c: elixir for elixir, cs in elixir2card.items() for c in cs}
card_list = list(card2elixir.keys())
idx2card = dict(enumerate(card_list))
card2idx = {c: i for i, c in idx2card.items()}
